title: Modeling and Control of a Unicycle Robot on Manifolds
description: Project webpage for the CDC paper by Adeel Akhtar and Mohamed Al Lawati
url: "https://gradslab.github.io"
baseurl: "/UnicycleOnManifolds"

markdown: kramdown

exclude:
  - README.md
  - Readme.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
